# Generated by Django 4.2.7 on 2026-09-10 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRATIVO', 'Administrativo'), ('MATRONA', 'Matrona'), ('MEDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('JEFATURA', 'Jefatura'), ('GERENCIA', 'Gerencia'), ('ADMIN_SISTEMA', 'Administrador del Sistema')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
