# Generated by Django 4.2.7 on 2026-09-10 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recien_nacidos', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alta_clinica_confirmada', models.BooleanField(default=False)),
                ('fecha_alta_clinica', models.DateTimeField(blank=True, null=True)),
                ('alta_administrativa_confirmada', models.BooleanField(default=False)),
                ('fecha_alta_administrativa', models.DateTimeField(blank=True, null=True)),
                ('certificado_generado', models.BooleanField(default=False)),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('fecha_certificado', models.DateTimeField(blank=True, null=True)),
                ('tipo_alta', models.CharField(choices=[('MADRE', 'Solo Madre'), ('RN', 'Solo Recién Nacido'), ('AMBOS', 'Madre y Recién Nacido')], max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('administrativo_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_administrativas', to=settings.AUTH_USER_MODEL)),
                ('medico_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_clinicas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='pacientes.paciente')),
                ('recien_nacido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='recien_nacidos.reciennacido')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAlta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True)),
                ('alta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='altas.alta')),
            ],
        ),
    ]
