# Generated by Django 4.2.7 on 2026-09-10 04:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$', 'RUT inválido')])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(60)])),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedenteClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controles_prenatales', models.JSONField(blank=True, default=list)),
                ('numero_controles', models.IntegerField(default=0)),
                ('numero_partos', models.IntegerField(default=0)),
                ('numero_cesareas', models.IntegerField(default=0)),
                ('numero_abortos', models.IntegerField(default=0)),
                ('tiene_hipertension', models.BooleanField(default=False)),
                ('tiene_diabetes_gestacional', models.BooleanField(default=False)),
                ('tiene_preclampsia', models.BooleanField(default=False)),
                ('otras_patologias', models.TextField(blank=True)),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente')),
            ],
        ),
    ]
