# Generated by Django 4.2.7 on 2026-09-21 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-?[\\dkK]$', 'RUT inválido')]),
        ),
    ]
