# Generated by Django 4.2.7 on 2026-09-10 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NATURAL', 'Parto Natural'), ('CESAREA', 'Cesárea'), ('INSTRUMENTAL', 'Parto Instrumental')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('duracion_estimada', models.IntegerField(default=120, help_text='Duración estimada en minutos')),
                ('tiene_complicaciones', models.BooleanField(default=False)),
                ('complicaciones', models.JSONField(blank=True, default=list)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EN_PROCESO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('enfermero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partos_enfermero', to=settings.AUTH_USER_MODEL)),
                ('matrona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partos_matrona', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partos_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ComplicacionParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HEMORRAGIA', 'Hemorragia'), ('SUFRIMIENTO_FETAL', 'Sufrimiento Fetal'), ('PROLAPSO_CORDON', 'Prolapso de Cordón'), ('DISTOCIA_HOMBROS', 'Distocia de Hombros'), ('ROTURA_UTERINA', 'Rotura Uterina'), ('OTROS', 'Otros')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_complicaciones', to='partos.parto')),
            ],
        ),
    ]
