# Generated by Django 4.2.7 on 2026-10-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='acompanamiento_parto',
            field=models.BooleanField(default=True, help_text='¿Contó con acompañamiento en preparto/parto?'),
        ),
        migrations.AddField(
            model_name='parto',
            name='alumbramiento_completo',
            field=models.BooleanField(default=True, help_text='¿Se verificó alumbramiento placentario completo?'),
        ),
        migrations.AddField(
            model_name='parto',
            name='apego_temprano',
            field=models.BooleanField(default=True, help_text='¿Se realizó apego temprano en sala?'),
        ),
        migrations.AddField(
            model_name='parto',
            name='estado_perineal',
            field=models.CharField(blank=True, choices=[('INTACTO', 'Intacto (Sin lesiones)'), ('EPISIOTOMIA', 'Episiotomía realizada'), ('DESGARRO', 'Desgarro perineal')], default='INTACTO', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='indicaciones_postparto',
            field=models.TextField(blank=True, default='', help_text='Evolución intraparto e indicaciones de puerperio', null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='inicio_presentacion',
            field=models.CharField(blank=True, choices=[('ESPONTANEO_CEFALICA', 'Espontáneo - Cefálica'), ('INDUCIDO_CEFALICA', 'Inducido - Cefálica'), ('PODALICA_OTRA', 'Podálica / Otra presentación')], default='ESPONTANEO_CEFALICA', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='paridad',
            field=models.CharField(blank=True, choices=[('PRIMIGESTA', 'Primigesta'), ('MULTIPARA', 'Multípara')], default='PRIMIGESTA', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='profesional_responsable',
            field=models.CharField(blank=True, default='Matrona de Turno', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='semanas_gestacion',
            field=models.PositiveIntegerField(blank=True, default=38, help_text='Semanas de gestación al ingreso', null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='tipo_anestesia',
            field=models.CharField(blank=True, choices=[('EPIDURAL', 'Epidural'), ('RAQUIDEA', 'Raquídea'), ('LOCAL', 'Local'), ('GENERAL', 'General'), ('NINGUNA', 'Sin Anestesia')], default='EPIDURAL', max_length=20, null=True),
        ),
    ]
