# Generated by Django 4.2.7 on 2026-09-10 04:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('partos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(blank=True, max_length=100, unique=True)),
                ('numero_interno', models.CharField(max_length=20, unique=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(6.0)])),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(60)])),
                ('apgar_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('apgar_5', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('apgar_10', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('condicion_al_nacer', models.CharField(choices=[('BUENA', 'Buena'), ('REGULAR', 'Regular'), ('MALA', 'Mala')], max_length=20)),
                ('derivado', models.BooleanField(default=False)),
                ('servicio_derivacion', models.CharField(blank=True, max_length=100)),
                ('fecha_derivacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_derivacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('HOSPITALIZADO', 'Hospitalizado'), ('DERIVADO', 'Derivado'), ('ALTA', 'Alta')], default='HOSPITALIZADO', max_length=20)),
                ('fecha_nacimiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente_madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='partos.parto')),
            ],
        ),
        migrations.CreateModel(
            name='ControlPosteriorRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_control', models.DateTimeField(auto_now_add=True)),
                ('vacuna_bcg', models.BooleanField(default=False)),
                ('fecha_bcg', models.DateField(blank=True, null=True)),
                ('lote_bcg', models.CharField(blank=True, max_length=50)),
                ('vacuna_hepatitis_b', models.BooleanField(default=False)),
                ('fecha_hepatitis_b', models.DateField(blank=True, null=True)),
                ('lote_hepatitis_b', models.CharField(blank=True, max_length=50)),
                ('tamizaje_neonatal', models.BooleanField(default=False)),
                ('fecha_tamizaje', models.DateField(blank=True, null=True)),
                ('resultado_tamizaje', models.CharField(blank=True, max_length=100)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.CharField(max_length=100)),
                ('recien_nacido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='recien_nacidos.reciennacido')),
            ],
        ),
    ]
