# Generated by Django 4.2.7 on 2026-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciennacido',
            name='numero_interno',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
