# Generated by Django 4.2.7 on 2026-09-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacidos', '0002_alter_reciennacido_numero_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciennacido',
            name='codigo_qr',
            field=models.TextField(blank=True),
        ),
    ]
