# Generated by Django 4.2.7 on 2026-10-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacidos', '0003_alter_reciennacido_codigo_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciennacido',
            name='circunferencia_craneana',
            field=models.DecimalField(blank=True, decimal_places=1, default=34.5, help_text='Perímetro cefálico (CC) en cm', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='grupo_rh',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('O+', 'O Rh(+)'), ('O-', 'O Rh(-)'), ('A+', 'A Rh(+)'), ('A-', 'A Rh(-)'), ('B+', 'B Rh(+)'), ('B-', 'B Rh(-)'), ('AB+', 'AB Rh(+)'), ('AB-', 'AB Rh(-)')], default='PENDIENTE', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='lactancia_primera_hora',
            field=models.BooleanField(default=True, help_text='¿Inició lactancia materna en la primera hora de vida?'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='profilaxis_completa',
            field=models.BooleanField(default=True, help_text='¿Recibió profilaxis ocular, cordón y Vitamina K?'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='requirio_oxigeno',
            field=models.BooleanField(default=False, help_text='¿Requirió oxígeno o estímulo de reanimación al nacer?'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='sexo',
            field=models.CharField(blank=True, choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino'), ('INDETERMINADO', 'Indeterminado')], default='FEMENINO', max_length=15, null=True),
        ),
    ]
